item.10000 = torch jack_o_lantern magma_block lantern blaze_rod lava_bucket camp_fire fire_charge
item.10001 = soul_torch
item.10002 = redstone_torch
item.10008 = glowstone

##METAL
item.10011 = iron_block iron_bars iron_door iron_trapdoor gold_block emerald_block diamond_block amethyst_block budding_amethyst small_amethyst_bud medium_amethyst_bud large_amethyst_bud amethyst_cluster quartz copper_block waxed_copper_block chiseled_copper copper_door copper_trapdoor cut_copper_slab cut_copper_stairs cut_copper copper_grate lightning_rod netherite_block iron_bars iron_door iron_trapdoor gold_bars gold_door heavy_weighted_pressure_plate light_weighted_pressure_plate gold_trapdoor 

##ICE 
item.10012 = ice snow snow_block packed_ice blue_ice 

##porous
##high drainage mid porosity
item.10013 = minecraft:sand dirt_path red_sand dirt
##mid drainage mid porosity
item.10014 = dirt wool white_wool light_gray_wool gray_wool light_blue_wool
##no drainage low porosity
item.10015 = sand_stone
##high drainage low porosity
item.10016 = minecraft:grass_block

##HARD and SHINY
item.10017=glass glass_pane lime_stained_glass stained_glass white_stained_glass orange_stained_glass magenta_stained_glass light_blue_stained_glass yellow_stained_glass pink_stained_glass gray_stained_glass light_gray_stained_glass cyan_stained_glass purple_stained_glass blue_stained_glass brown_stained_glass green_stained_glass red_stained_glass black_stained_glass stained_glass_pane white_stained_glass_pane orange_stained_glass_pane magenta_stained_glass_pane light_blue_stained_glass_pane yellow_stained_glass_pane lime_stained_glass_pane pink_stained_glass_pane gray_stained_glass_pane light_gray_stained_glass_pane cyan_stained_glass_pane purple_stained_glass_pane blue_stained_glass_pane brown_stained_glass_pane green_stained_glass_pane red_stained_glass_pane black_stained_glass_pane tinted_glass flint_and_steel copper_ingot

#glowing whatever color they are
item.10037 = eye_of_ender glow_ink_sac glow_berries glowstone_dust blaze_powder blaze_rod

