blend.clrwl_gbuffers.colortex1=off
blend.clrwl_gbuffers_translucent.colortex1=off

#if COLORWHEEL_OIT == 1
	oit = true

	oit.gbuffers.coefficientRanks = 3

	oit.gbuffers.colortex0 = 0

	oit.gbuffers.colortex1 = frontmost
	oit.gbuffers.colortex1.format = RGBA8
#endif

