##whitelist for texture filtering fix
entity.20000 = minecraft:item

##blacklist for not texture filtering on
entity.20001 = minecraft:frog

#hard coded entities that glow like fire
entity.20010 = entity_flame blaze 

#hard coded glowing item frame
entity.20011 = glow_item_frame  


#hard coded entities that glow whatever color
entity.20012 = glow_squid beacon_beam eye_of_ender fire_charge fireball \
#if GLOWING_ROCKETS == 1
firework_rocket
#endif

#nametags
entity.20013 =  minecraft:name_tag

#don't voxelize
##entity.10100 = item_frame 

#player
entity.20014 = player







#macro textures
##Macro Roughness assignments
##/*
##The materials are arranged in a 4x4 atlas.
##	metal / stone / concrete / dirt
##	blank / porous-stone / wood-grain / plant-leaf
##	fur / fabric / skin-leather / hair-short
##	glass / cystal / wax/slime / grass-organic-dirt
##*/
entity.20100 =  iron_golem
entity.20101 =  block_name_example
entity.20102 =  block_name_example 
entity.20103 =  block_name_example 

entity.20104 =  block_name_example 
entity.20105 =  block_name_example 
entity.20106 =  creaking
entity.20107 =  block_name_example 

entity.20108 =  horse sheep
entity.20109 =  block_name_example 
entity.20110 =  pig 
entity.20111 =  cat wolf 

entity.20112 =  block_name_example 
entity.20113 =  block_name_example 
entity.20114 =  slime 
entity.20115 =  block_name_example 








## MAIN COLOR OVERRIDES LIST - ENTITIES (1 of 3 Lists)

## (add modded blocks that don't auto detect the right color here. The main listings are Saturated(bold colors), Unsaturated(white-ish), Dim, and fire is higher up. Let me know what blocks need added, and I'll add then to the next update. Torches are listed higher up.

## Blocks need to be added to block.properties to glow when placed AND item.properties to glow in hand
## Entities & Block Entities need to be added to entities.properties to glow when placed AND item.properties to glow in hand

## SATURATED COLORS (very colorful)

## RED  vec3(1.,.0,.0);
entity.10113 = block_name_example 
## RED_ORANGE  vec3(1.,.25,.0);
entity.10101 =  block_name_example
## ORANGE  vec3(1.,.5,.0);
entity.10102 =  block_name_example
## YELLOW  vec3(1.,1.,.0);
entity.10103 =  block_name_example 
## YELLOW_GREEN  vec3(.5,1.,.0);
entity.10104 =  block_name_example
## GREEN  vec3(.0,1.,.0);
entity.10105 =  block_name_example
## GREEN_CYAN  vec3(.0,1.,.5);
entity.10106   =  block_name_example
## CYAN  vec3(.0,1.,1.);
entity.10107 =  block_name_example
## BLUE_CYAN  vec3(.0,.5,1.);
entity.10108 =  block_name_example
## BLUE  vec3(.0,.0,1.);
entity.10109 =  block_name_example
## PURPLE  vec3(.5,.0,1.);
entity.10110    =  block_name_example
## MAGENTA  vec3(1.,.0,1.);
entity.10111  =  block_name_example
## RED_MAGENTA  vec3(1.,.0,.5);
entity.10112  =  block_name_example

## UN-SATURATED COLORS (half white)

## LIGHT_RED  vec3(1.,.5,.5);
entity.10120  =  block_name_example 
## LIGHT_RED_ORANGE  vec3(1.,.62,.5);
entity.10121  =  block_name_example
## LIGHT_ORANGE  vec3(1.,.75,.5);
entity.10122 =  block_name_example
## LIGHT_YELLOW  vec3(1.,1.,.5);
entity.10123 =  block_name_example
## LIGHT_YELLOW_GREEN  vec3(.75,1.,.5);
entity.10124 =  block_name_example
## LIGHT_GREEN  vec3(.5,1.,.5);
entity.10125 =  block_name_example
## LIGHT_GREEN_CYAN  vec3(.5,1.,.75);
entity.10126 =  block_name_example
## LIGHT_CYAN  vec3(.5,1.,1.);
entity.10127 =  block_name_example
## LIGHT_BLUE_CYAN  vec3(.5,.75,1.);
entity.10128 =  block_name_example
## LIGHT_BLUE  vec3(.5,.5,1.);
entity.10129 =  block_name_example
## LIGHT_PURPLE  vec3(.75,.5,1.);
entity.10130 =  block_name_example
## LIGHT_MAGENTA  vec3(1.,.5,1.);
entity.10131 =  block_name_example
## LIGHT_RED_MAGENTA  vec3(1.,.5,.75);
entity.10132 =  block_name_example

## DIM COLORS (not very bright)

## DIM_RED  vec3(.5,.0,.0);
entity.10140 =  block_name_example simplycozymod:christmas_tree
## DIM_RED_ORANGE  vec3(.5,.12,.0);
entity.10141 =  block_name_example
## DIM_ORANGE  vec3(.5,.25,.0);
entity.10142 =  block_name_example
## DIM_YELLOW  vec3(.5,.5,.0);
entity.10143 =  block_name_example
## DIM_YELLOW_GREEN  vec3(.25,.5,.0);
entity.10144 =  block_name_example
## DIM_GREEN  vec3(.0,.5,.0);
entity.10145 =  block_name_example
## DIM_GREEN_CYAN  vec3(.0,.5,.25);
entity.10146 =  block_name_example
## DIM_CYAN  vec3(.0,.5,.5);
entity.10147 =  block_name_example
## DIM_BLUE_CYAN  vec3(.0,.25,.5);
entity.10148 =  block_name_example
## DIM_BLUE  vec3(.0,.0,.5);
entity.10149 =  block_name_example
## DIM_PURPLE  vec3(.25,.0,.5);
entity.10150 =  block_name_example
## DIM_MAGENTA  vec3(.5,.0,.5);
entity.10151 =  block_name_example
## DIM_RED_MAGENTA  vec3(.5,.0,.25);
entity.10152 =  block_name_example

## WHITE  vec3(1.);
entity.10160 =  block_name_example simplycozymod:modern_light simplycozymod:modern_wall_light
##DIM_WHITE vec3(.5);
entity.10161 =  block_name_example




